version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/registration
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: bigAdmin
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bigAdmin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: