version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - maildev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/registration
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: bigAdmin
    volumes:
      - ./src:/app/src
      - ./target/classes:/app/target/classes
  
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bigAdmin

volumes:
  pgdata:
  frontend_node_modules: